package com.stylemirror.core.data.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * All Room schema migrations for [StyleMirrorDatabase].
 *
 * Migration 0→1 is the initial creation. Room does not run migrations on a
 * fresh install — `CREATE TABLE IF NOT EXISTS` is generated by Room's schema
 * export; this migration exists so migration tests can exercise the SQL
 * explicitly and catch any schema drift.
 */
object StyleMirrorMigrations {
    val MIGRATION_1_1: Migration =
        object : Migration(1, 1) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // Identity migration — no schema change from v1 to v1.
                // Present so the migration registry is non-empty and can be
                // extended when v2 lands.
            }
        }

    /** Full DDL for schema version 1. Used by MigrationTestHelper. */
    val CREATE_V1_SQL: List<String> =
        listOf(
            """
            CREATE TABLE IF NOT EXISTS messages (
                id TEXT NOT NULL PRIMARY KEY,
                partner_id TEXT NOT NULL,
                content TEXT NOT NULL,
                speaker TEXT NOT NULL,
                display_name TEXT,
                sent_at_epoch_ms INTEGER NOT NULL,
                import_session_id TEXT,
                FOREIGN KEY (import_session_id) REFERENCES import_sessions(id) ON DELETE SET NULL
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS index_messages_import_session_id ON messages(import_session_id)",
            """
            CREATE TABLE IF NOT EXISTS style_fingerprints (
                rowid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                version INTEGER NOT NULL,
                created_at_epoch_ms INTEGER NOT NULL,
                sample_size INTEGER NOT NULL,
                partner_scope_id TEXT,
                fingerprint_json TEXT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS feedback_signals (
                id TEXT NOT NULL PRIMARY KEY,
                candidate_id TEXT NOT NULL,
                fingerprint_version INTEGER NOT NULL,
                type TEXT NOT NULL,
                created_at_epoch_ms INTEGER NOT NULL,
                edited_content TEXT,
                discard_reason TEXT
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS import_sessions (
                id TEXT NOT NULL PRIMARY KEY,
                partner_id TEXT NOT NULL,
                source_type TEXT NOT NULL,
                started_at_epoch_ms INTEGER NOT NULL,
                completed_at_epoch_ms INTEGER,
                message_count INTEGER NOT NULL
            )
            """.trimIndent(),
        )

    val ALL: Array<Migration> = arrayOf(MIGRATION_1_1)
}
