package com.stylemirror.core.data.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * All Room schema migrations for [StyleMirrorDatabase].
 *
 * Migration 0→1 is the initial creation. Room does not run migrations on a
 * fresh install — `CREATE TABLE IF NOT EXISTS` is generated by Room's schema
 * export; this migration exists so migration tests can exercise the SQL
 * explicitly and catch any schema drift.
 */
object StyleMirrorMigrations {
    val MIGRATION_1_1: Migration =
        object : Migration(1, 1) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // Identity migration — no schema change from v1 to v1.
                // Present so the migration registry is non-empty and can be
                // extended when v2 lands.
            }
        }

    /**
     * v2 (画像 v2 / ADR-0005) — adds:
     *  - `style_fingerprints.behavior_rules TEXT NOT NULL DEFAULT ''`
     *  - new table `style_corpus_samples`
     *
     * No data backfill: v1 rows get an empty `behavior_rules` and no corpus
     * samples; UI / CandidateGenerator detect this and fall back to v1 prompt
     * shape until the user re-profiles or evolves.
     */
    val MIGRATION_1_2: Migration =
        object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "ALTER TABLE style_fingerprints ADD COLUMN behavior_rules TEXT NOT NULL DEFAULT ''",
                )
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS style_corpus_samples (
                        rowid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        fingerprint_version INTEGER NOT NULL,
                        partner_scope_id TEXT,
                        text TEXT NOT NULL,
                        scenario TEXT NOT NULL,
                        created_at_epoch_ms INTEGER NOT NULL,
                        deleted_at_epoch_ms INTEGER
                    )
                    """.trimIndent(),
                )
                db.execSQL(
                    "CREATE INDEX IF NOT EXISTS index_style_corpus_samples_fingerprint_version " +
                        "ON style_corpus_samples(fingerprint_version)",
                )
                db.execSQL(
                    "CREATE INDEX IF NOT EXISTS index_style_corpus_samples_scenario " +
                        "ON style_corpus_samples(scenario)",
                )
            }
        }

    /** Full DDL for schema version 1. Used by MigrationTestHelper. */
    val CREATE_V1_SQL: List<String> =
        listOf(
            """
            CREATE TABLE IF NOT EXISTS messages (
                id TEXT NOT NULL PRIMARY KEY,
                partner_id TEXT NOT NULL,
                content TEXT NOT NULL,
                speaker TEXT NOT NULL,
                display_name TEXT,
                sent_at_epoch_ms INTEGER NOT NULL,
                import_session_id TEXT,
                FOREIGN KEY (import_session_id) REFERENCES import_sessions(id) ON DELETE SET NULL
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS index_messages_import_session_id ON messages(import_session_id)",
            """
            CREATE TABLE IF NOT EXISTS style_fingerprints (
                rowid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                version INTEGER NOT NULL,
                created_at_epoch_ms INTEGER NOT NULL,
                sample_size INTEGER NOT NULL,
                partner_scope_id TEXT,
                fingerprint_json TEXT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS feedback_signals (
                id TEXT NOT NULL PRIMARY KEY,
                candidate_id TEXT NOT NULL,
                fingerprint_version INTEGER NOT NULL,
                type TEXT NOT NULL,
                created_at_epoch_ms INTEGER NOT NULL,
                edited_content TEXT,
                discard_reason TEXT
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS import_sessions (
                id TEXT NOT NULL PRIMARY KEY,
                partner_id TEXT NOT NULL,
                source_type TEXT NOT NULL,
                started_at_epoch_ms INTEGER NOT NULL,
                completed_at_epoch_ms INTEGER,
                message_count INTEGER NOT NULL
            )
            """.trimIndent(),
        )

    val ALL: Array<Migration> = arrayOf(MIGRATION_1_1, MIGRATION_1_2)
}
